// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }





// import { ReactNode } from 'react';
// import { Toaster } from 'sonner';
//  // or "sonner"
// import Navbar from '@/components/Navbar';
// import Sidebar from '@/components/Sidebar';

// export default function RootLayout({ children }: { children: ReactNode }) {
//   return (
//     <html lang="en">
//       <body className="flex h-screen">
//         <Sidebar />
//         <div className="flex flex-col flex-1">
//           <Navbar />
//           <main className="p-6">{children}</main>
//         </div>
//         <Toaster /> 
//       </body>
//     </html>
//   );
// }

// app/layout.tsx
import './globals.css';
import { Toaster } from 'sonner';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
      <Toaster position='top-center' style={{width:"26%"}} />
    </html>
  );
}
